### ISSUE TITLE
Mocking problem - maybe a 🐞 in wiki or it's just me 😉

### ISSUE THREAD

**Issue by Adam-it** [microsoftgraph/msgraph-developer-proxy#102]
### Problem I found

While testing the tool I tried mocking. What I did was adding a `responses.json` in my workspace (the dev proxy was also working in the same directory) and my mock was (I wanted to always fail on getting current user info)
```
{
  "responses": [
    {
      "url": "/v1.0/me",
      "method": "GET",
      "responseCode": 500
    }
  ]
}
```

I hope I done it correctly 🤔. I tried to follow the guidance provided in the wiki here (https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Mock-responses)

Unfortonatly when testing my app with ms dev proxy it turned out it was not respecting (using) my mocks. 
![image](https://user-images.githubusercontent.com/58668583/211197722-b790e129-5803-4ebb-82d1-e932a7ee586e.png)

What I had to correct is turning the `/v1.0/me` to full URL `https://graph.microsoft.com/v1.0/me` so my mock was now 
```
{
  "responses": [
    {
      "url": "https://graph.microsoft.com/v1.0/me",
      "method": "GET",
      "responseCode": 500
    }
  ]
}
```

After that it worked properly and was using my mocked response 
![image](https://user-images.githubusercontent.com/58668583/211197846-468415fe-9c33-4156-a3fa-c4366fab3bd0.png)

But according to the examples in the wiki my previous mock should also be ok right? Maybe the wiki should be updated or maybe I was doing something wrong 😉

### Quick checking my problem with the code

Checking this quickly with the code I think it is due to this part
https://github.com/microsoftgraph/msgraph-developer-proxy/blob/8585d681411836a02d144b8238e0644e9ecc4aa7/msgraph-developer-proxy/ChaosEngine.cs#L431-L434

Where we compare the exact URL. Maybe this could be updated to `request.Url.IndexOf(mockResponse.Url, StringComparison.OrdinalIgnoreCase) >= 0`  🤔

### What I would suggest (if I am right 😉)

Leave it as is but just update the wiki 👍

### BTW 

Sorry I didn't find time to test it out sooner. Congrats on the awesome Hackathon result 🤩 You all rock and I hope to use msgraph developer proxy as an example to organize this kind of hackathon where I work 😉

**Comment by waldekmastykarz** [comment]
Do you recall which version of the proxy you used? If I recall correctly we changed this behavior in v0.3 that we released recently and it's plausible that we missed updating the docs. Sorry, that's on us, and thank you for pointing it out. We'll fix it asap.

**Comment by Adam-it** [comment]
No problem.  It's just the problem in the wiki, in the resposnes.json file you have in the repo it is ok.
I am using the `v0.3.0` which I downloaded today

**Comment by waldekmastykarz** [comment]
Thank you for bringing it to our attention. We'll fix it right away

**Comment by garrytrinder** [comment]
Thanks for reporting @Adam-it apologies for the trouble. I'll take a look.

**Comment by Adam-it** [comment]
awesome quick fix in the wiki. Thanks @garrytrinder 👍
