### ISSUE TITLE
Update correct instruction to start proxy

### ISSUE THREAD

**Issue by rabwill** [microsoftgraph/msgraph-developer-proxy#105]
To start the proxy for the first time, [see here](https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Using-the-Microsoft-Graph-Developer-Proxy-for-the-first-time#-start-the-proxy-for-the-first-time), it is instructed to `Open up a terminal session and change to the samples directory`. This step is unnecessary.

**Comment by rabwill** [comment]
Also adding another readme issue here so I don't spam this repo ;)

The env.js file is already created and my app id is updated when I choose to run the setup.ps1, yet the readme only says about the manual creation of env.js file. I think this should be mentioned as well.

**Comment by waldekmastykarz** [comment]
> To start the proxy for the first time, [see here](https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Using-the-Microsoft-Graph-Developer-Proxy-for-the-first-time#-start-the-proxy-for-the-first-time), it is instructed to `Open up a terminal session and change to the samples directory`. This step is unnecessary.

As we're saying in the first paragraph, the tutorial is about running the proxy against the sample app, which is why we ask you to change the working folder.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/11164679/211256628-6d310e00-9470-4408-8cc6-93a3fa3751e9.png">

Could it be that the title is not clear and gives you the impression that it's a generic first time run, rather than first time run with the sample app?

> The env.js file is already created and my app id is updated when I choose to run the setup.ps1, yet the readme only says about the manual creation of env.js file.

Manual is an alternative option to PowerShell rather than a follow-up. We should make that clearer. Thank you for bringing it up.

**Comment by garrytrinder** [comment]
Thank you for reporting this @rabwill apologies for the trouble.

I'll take a look.

**Comment by garrytrinder** [comment]
> The env.js file is already created and my app id is updated when I choose to run the setup.ps1, yet the readme only says about the manual creation of env.js file. I think this should be mentioned as well. [`main`/samples/readme.md](https://github.com/microsoftgraph/msgraph-developer-proxy/blob/main/samples/readme.md?rgh-link-date=2023-01-09T00%3A43%3A07Z)

I've raised a PR to add a remark to inform the reader that the script will create the `env.js` file.

https://github.com/microsoftgraph/msgraph-developer-proxy/pull/108

Does this resolve the confusion @rabwill ? Feel free to comment on the PR.

**Comment by garrytrinder** [comment]
My preference is title number 4 btw 😊

> The Basics of Testing Microsoft Graph Developer Proxy with a Sample App: A Step-by-Step Guide

**Comment by waldekmastykarz** [comment]
How about "Getting started guide: test a sample app with the Graph Developer Proxy"?

**Comment by garrytrinder** [comment]
As the page we are suggesting to rename is a sub-page of the `Get started` page, I don't think we need to repeat that in the title, I think we can drop `Getting started guide:` but I like the rest of your suggestion. 

`Test a sample app with Microsoft Graph Developer Proxy` is clear what it is and sets the expectations correctly.

**Comment by garrytrinder** [comment]
@rabwill I've updated the tutorial to reflect the comments made in this issue.

Your feedback is most welcome 👍

**Comment by waldekmastykarz** [comment]
> As the page we are suggesting to rename is a sub-page of the `Get started` page, I don't think we need to repeat that in the title, I think we can drop `Getting started guide:` but I like the rest of your suggestion.

Is that obvious though, when you land on the page from an external link? I suspect that you'd focus on the title of the page first and could possibly miss the ToC on the side altogether, losing some of the context inferred from the page structure.

**Comment by rabwill** [comment]
Thanks folks for clarifying.  was confused with the title thinking I had to start the proxy like ngrok. It now makes sense that it is started against a sample. 
I like @waldekmastykarz 's suggestion **Getting started guide: test a sample app with the Graph Developer Proxy** as well as the 4th one suggested by @garrytrinder :) Sorry I am not helping.

Alternatively I can also help suggest one Yeeh :D 
**Testing sample applications with Microsoft Graph Developer Proxy: A Beginner's Guide**

**Comment by garrytrinder** [comment]
Closing this as I have made updates to the wiki based on the feedback given.

Thanks again for reporting this @rabwill this has really helped us improve our docs 👍
