### ISSUE TITLE
Unable to view all guides on wiki

### ISSUE THREAD

**Issue by rabwill** [microsoftgraph/msgraph-developer-proxy#106]
I am currently [exploring the tool](https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/How-to-guides) and is unable to go to wiki under [Simulate behaviours](https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/How-to-guides#simulate-behaviours). It says `You do not have permission to update this wiki.`

**Comment by rabwill** [comment]
Yes @waldekmastykarz I am signed in using SSO for corp account. I tried again, it's still the same issue.

**Comment by garrytrinder** [comment]
Got it. We had a broken link.

I've updated the link, so should be working for you now @rabwill

**Comment by waldekmastykarz** [comment]
Can we close this issue as fixed @garrytrinder?
