### ISSUE TITLE
[Bug]: `msgraph-developer-proxy is damaged and cannot be opened`

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#119]
From 0.2.3 onwards, I am unable to start the proxy on macOS Monterey 12.6.2 (21G320), as I receive the below error.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/11563347/213658090-d91f4ba8-86fa-4cb5-8e3f-43bbb38f4c93.png">

0.2.1 and 0.2.2 releases work fine.

**Comment by gavinbarron** [comment]
Interestingly v0.3.0 works on my MacBook Air (Intel) running macOS Monterey 12.6.2 (21G320)

**Comment by leeford** [comment]
Hi, I can run it on my MacBook Pro (M1 Max):

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/472320/213886397-93497ba7-9644-4fe7-81ba-42495ea363e2.png">

Out of interest, what is your SHA256 sum @garrytrinder, was wondering if its different in anyway?

**Comment by waldekmastykarz** [comment]
We compared the checksum between the working and not-working version and they were the same @leeford

**Comment by garrytrinder** [comment]
Thanks for checking @gavinbarron @leeford 

Back to the drawing board 🤔

**Comment by gavinbarron** [comment]
@garrytrinder what processor is your Mac running? I seem to recall there being some challenges with lots of software when Apple pivoted to using their own silicon.

**Comment by toddanglin** [comment]
I fresh installed v0.3.0 on macOS Ventura 13.1 running on Apple M1 and everything seems to work as expected (using default zsh terminal). Definitely sounds like something uniquely corrupted in your environment. Have you tried the general macOS guidance for fixing "[XX] is damaged and can't be opened"? (ex: https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/)

**Comment by waldekmastykarz** [comment]
> @garrytrinder what processor is your Mac running? I seem to recall there being some challenges with lots of software when Apple pivoted to using their own silicon.

If I recall correctly, @garrytrinder is on Intel

**Comment by garrytrinder** [comment]
Fixed!!

It appears that Gatekeeper had put the file into quarantine for some reason.

To remove the file from quarantine, execute the following in a terminal prompt:

```sh
xattr -d com.apple.quarantine ~/msgraph-developer-proxy/msgraph-developer-proxy
```

Thanks for the link to the article @toddanglin 👍

**Comment by garrytrinder** [comment]
Reopening as I am having issue with the proxy that I think is still related this.

Although I can now execute the proxy, the certificate is not saved to the `.config/msgraph-developer-proxy` folder and is not added into keychain, this results in SSL errors.

Interestingly, I can build v0.3 locally in Visual Studio for Mac and run the built executable which works as expected.

**Comment by waldekmastykarz** [comment]
Hey @garrytrinder, is this still an issue for you?

**Comment by garrytrinder** [comment]
Tested on a fresh install of macOS Ventura and all is working fine with `v0.8`.
