### ISSUE TITLE
[How-to guide]: Configure Nerd Fonts in console output

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#124]
In v0.4, we will release a new more readable console output with the ability to configure Nerd Fonts to change text labels to icons so we should include a guide to provide how to do this.

**Comment by garrytrinder** [comment]
We should also include ASCII icons here.

**Comment by waldekmastykarz** [comment]
An extra consideration is that folks should use a variable-width Nerd Font because fixed-width Nerd Fonts lead to misalignment in the terminal. This is a known issue with Nerd Fonts and related to the width of certain glyphs.
