### ISSUE TITLE
[Suggestion]: Shorten the executable name to `mgdp`

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#125]
`msgraph-developer-proxy` is quite long, we should consider renaming it to `mgdp` to make the proxy executable more concise and memorable.

**Comment by sebastienlevert** [comment]
I'm also in favor! I haven't seen popping up for Windows on my side.

**Comment by gavinbarron** [comment]
I like this idea, should be dead easy too.

**Comment by sebastienlevert** [comment]
Based on the discussion we had earlier. Should this be in the Feb scope? @waldekmastykarz @gavinbarron @garrytrinder

**Comment by waldekmastykarz** [comment]
After we did this, let's ensure we update all documentation to properly reflect the new name

**Comment by garrytrinder** [comment]
> After we did this, let's ensure we update all documentation to properly reflect the new name

I'll create a `05-release` branch on the wiki repo to prepare for documentation changes in next release.

**Comment by garrytrinder** [comment]
Branch create, name change commit made, and pushed to origin 👍
