### ISSUE TITLE
Simplify plugin config

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#145]
Plugins can take configuration settings to change its behaviour. Configuration is set using the `configSection` property. `configSection` accepts a string, which acts as a reference to a configuration object. Configuration objects are stored at the root level of the `appsettings` object.

Seperating configuration from the plugin impacts readability. As the file grows over time, it will be harder for developers to view full plugin definition at a glance.

## Current schema

In the below example, the `mocksPlugin` object is located seperate to the plugin object. 

The current schema:

```json
{
  "plugins": [
	{
      "name": "MockResponsePlugin",
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "configSection": "mocksPlugin",
      "disabled": false
    }
  ],
  "mocksPlugin": {
    "mocksFile":  "responses.json"
  },
}
```

## Suggested schema

I would like to suggest removing the `configSection` property and replace with a new `config` property. The `config` property will be in-line into the plugin object.

The suggested schema:

```json
{
  "plugins": [
	{
      "name": "MockResponsePlugin",
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "config": {
	      "mocksFile":  "responses.json"
	  },
      "disabled": false
    }
  ]
}
```

**Comment by waldekmastykarz** [comment]
I wonder if this is possible with regards to how we deserialize the config. I'll let @gavinbarron respond to this but my gut feeling says that we separate it for a reason.

**Comment by gavinbarron** [comment]
You're correct @waldekmastykarz 

Dotnet provides a really nice API when it comes to configuration binding. By using a string property as a pointer to the rest of the config for a plugin loading that fragment of config bound to a strong type is this simple: 
In [Plugin Loader](https://github.com/microsoftgraph/msgraph-developer-proxy/blob/d59c25145851234746be09b5e4ca2beb44225f6a/msgraph-developer-proxy/PluginLoader.cs#L47):
```csharp
Configuration.GetSection(h.ConfigSection)
```
Then in a [plugin](https://github.com/microsoftgraph/msgraph-developer-proxy/blob/d59c25145851234746be09b5e4ca2beb44225f6a/msgraph-developer-proxy-plugins/RandomErrors/RandomErrorPlugin.cs#L184)
```csharp
configSection?.Bind(_configuration);
```
This gives us benefits like automatic configuration updates should the file be changed without restarting the app and eliminates a lot of very nasty, and error prone parsing code in favor of battle hardened and maintained library code.

I agree that the config is a little unwieldy, but IMO the price is worth it for easy of coding and lower cost of maintenance.

**Comment by waldekmastykarz** [comment]
Thanks for the additional info, @gavinbarron. I suggest we keep it as-is for now.
