### ISSUE TITLE
[Bug] New Version detection appears broken.

### ISSUE THREAD

**Issue by gavinbarron** [microsoftgraph/msgraph-developer-proxy#150]
I ran up version 0.3.0 this morning, well after our new v0.4.0 release was out and I was not informed that there was a new version available
![image](https://user-images.githubusercontent.com/7122716/215842412-acbcf920-ab49-4f58-ae37-36746e7074dd.png)

**Comment by waldekmastykarz** [comment]
I can repro the bug and it seems related to us being unable to correctly determine current proxy version after changing the project structure.
