### ISSUE TITLE
When using `--no-mocks` we should not output the WARNING

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-developer-proxy#161]
When using the proxy this way ` msgraph-developer-proxy --port 8080 --failure-rate 10 --no-mocks --allowed-errors 429` we are getting the following output: 

```
Sébastien Levert@SLEVERT-LENOVO  ~  msgraph-developer-proxy --port 8080 --failure-rate 10 --no-mocks --allowed-errors 429
WARNING: File responses.json not found in the current directory. No mocks will be provided
```

When using the proxy without mocks, we should not be warned about it not using mocks!

**Comment by waldekmastykarz** [comment]
Good point. For sure. I call it a bug
