### ISSUE TITLE
[Bug🐞/or I am doing something completely wrong🤔] - mocking response is not send

### ISSUE THREAD

**Issue by Adam-it** [microsoftgraph/msgraph-developer-proxy#164]
I have a test WPF app that sends request to `https://graph.microsoft.com/v1.0/me`. 
When I use chaos mode and a failure is generated I get the correct behavior, which means I get the error in the response 
![image](https://user-images.githubusercontent.com/58668583/216793859-f9138d73-7c13-4bb5-aae7-e3a608dffd99.png)

When I use the same mocking the response to return `500` it seems the request is caught but I as a response I don't get the error from the proxy but I get response from graph API
![image](https://user-images.githubusercontent.com/58668583/216793909-d502b367-69b7-442e-bea0-641e27abc7f9.png)

this is my `mock.json` file:
```
{
  "responses": [
    {
      "url": "https://graph.microsoft.com/v1.0/me",
      "method": "GET",
      "responseCode": 500
    },
    {
      "url": "https://customapiendpoint/test/gettest",
      "method": "GET",
      "responseCode": 500
    }
  ]
}
```

Am I missing something or is it a bug?
TBH the same kind of scenario worked fine in v0.3 meaning I got an error in the response when mocking.

**Comment by waldekmastykarz** [comment]
Could you please share with us your appsettings.json and mock.json so that we can repro it?

**Comment by Adam-it** [comment]
`mock.json` file
```
{
  "responses": [
    {
      "url": "https://graph.microsoft.com/v1.0/me",
      "method": "GET",
      "responseCode": 500
    },
    {
      "url": "https://customapiendpoint/test/gettest",
      "method": "GET",
      "responseCode": 500
    }
  ]
}
```

`appsettings.json`:
```
{
  "plugins": [
    {
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "name": "GraphSelectGuidancePlugin",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "name": "GraphBetaSupportGuidancePlugin",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "name": "GraphSdkGuidancePlugin",
      "urlsToWatch": [
        "https://graph.microsoft.com/v1.0/*",
        "https://graph.microsoft.com/beta/*",
        "https://graph.microsoft.us/v1.0/*",
        "https://graph.microsoft.us/beta/*",
        "https://dod-graph.microsoft.us/v1.0/*",
        "https://dod-graph.microsoft.us/beta/*",
        "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
        "https://microsoftgraph.chinacloudapi.cn/beta/*"
      ]
    },
    {
      "configSection": "mocksPlugin",
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "name": "MockResponsePlugin",
      "disabled": false
    },
    {
      "configSection": "randomErrorsPlugin",
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "name": "RandomErrorPlugin",
      "disabled": false
    }
  ],
  "urlsToWatch": [
    "https://graph.microsoft.com/v1.0/*",
    "https://graph.microsoft.com/beta/*",
    "https://graph.microsoft.us/v1.0/*",
    "https://graph.microsoft.us/beta/*",
    "https://dod-graph.microsoft.us/v1.0/*",
    "https://dod-graph.microsoft.us/beta/*",
    "https://microsoftgraph.chinacloudapi.cn/v1.0/*",
    "https://microsoftgraph.chinacloudapi.cn/beta/*",
    "https://*.sharepoint.*/*_api/*",
    "https://*.sharepoint.*/*_vti_bin/*",
    "https://*.sharepoint-df.*/*_api/*",
    "https://*.sharepoint-df.*/*_vti_bin/*",
    "https://customapiendpoint/test/gettest"
  ],
  "mocksPlugin": {
    "mocksFile":  "responses.json"
  },
  "randomErrorsPlugin": {
    "rate": 50,
    "allowedErrors": [ 429, 500, 502, 503, 504, 507 ]
  },
  "labelMode": "text",
  "logLevel": "info"
}
```

**Comment by waldekmastykarz** [comment]
It seems like in your config you're pointing to responses.json but your mock file is named mock.json. Could this be the issue?

**Comment by waldekmastykarz** [comment]
You're right and I can repro the error. Let me see what's wrong. Thank you for reporting it and sorry for the trouble.

**Comment by Adam-it** [comment]
> You're right and I can repro the error. Let me see what's wrong. Thank you for reporting it and sorry for the trouble.

That's totally ok. Let me know if you need any help. I started debugging it anyway to get to know the plugin approach for my plugin but I doze off in front of the laptop 😅.
Better luck next weekend

**Comment by Adam-it** [comment]
> I found the issue and submitted a PR. We'll try to get it processed asap and perhaps could release a beta to test it early.

Cool thanks 👍
I will test it from debug today over the night from the branch from your PR to double check if it's working on 'my machine' as well 😅.
Thanks for your quick reaction to the issue. You rock 👍

**Comment by Adam-it** [comment]
@waldekmastykarz I tested your changes done in the PR and in general it works 👍. The only difference I see is that in v0.3 the proxy also returned some `response.content` added to the error, now it is empty.
So previously in `response.content` for `500` I got something like this
![image](https://user-images.githubusercontent.com/58668583/217395067-53762089-1631-417c-9fcc-4c4a202dd39b.png)

now actually the `content` is empty. BUT I guess this is fine as long as the status code is correctly returned which is `500` (InternalServerError), so I sliglthy modified my test app to print the status code as well and now my output is like

![image](https://user-images.githubusercontent.com/58668583/217394837-a46cb3af-8737-40bc-94d8-c4cdcca8eec0.png)


Totally fine if you ask me 😉. But just wanted to let you know 👍.
Awesome work 👍 Thank you for your ASAP response on this one 🤩 Can't wait for this to be merged since it is also needed for my custom plugin (but no rush 😉)
