### ISSUE TITLE
Naming convention for options to avoid collisions

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#168]
If two plugins use the same options, it will lead to a collision on runtime, breaking the proxy.

@gavinbarron @sebastienlevert @garrytrinder: Should we consider defining naming convention/guidance for plugins to avoid this?

**Comment by waldekmastykarz** [comment]
I ran into this when building a generic chaos plugin that would work with any API. Both plugins expose failure rate as an option which collides on runtime. If you had an app that uses both Graph and other APIs and wanted to test them all, you'd enable both plugins which would throw a runtime exception.

**Comment by sebastienlevert** [comment]
So... I feel they should be using the "same" option. That way your plugin could plug into the option of another plugin to infer context, options, config... Is there a way to "merge" them? That way both plugins use the same value for their option?

**Comment by waldekmastykarz** [comment]
The problem is that the option is mapped to a class property that's defined in a class that defines the plugin, and one plugin doesn't know about another, so I don't think if that would be possible. Unless there's a way for us to enumerate all registered options and get a value that way we're stuck. And even then we'd have to consider a possibility that two plugins might use the same option name with a different value type which would still lead to issues.

**Comment by waldekmastykarz** [comment]
Another scenario where this issue is relevant is when we get more generic plugins that people could choose to load multiple times, each with different settings. An example of this could be the generic chaos handler I've been experimenting with where you could instantiate it multiple times each with settings for a specific API that you app is using. In such case, the plugin would collide with other instances of itself. Reusing existing options could be a way out here because each instance uses options of the same type here.

**Comment by gavinbarron** [comment]
I like the re-use idea, it bears some experimentation, as I'm not sure if the reading will work for a second option in a collision as the object instance would not have been added to the CommandHandler.

Naming conventions would be another useful tool to help prevent the collisions between.

**Comment by waldekmastykarz** [comment]
> I like the re-use idea, it bears some experimentation, as I'm not sure if the reading will work for a second option in a collision as the object instance would not have been added to the CommandHandler.

Valid point. I think, in such case, we'd almost have to look at swapping the reference to point to the one that's already registered and originating from another instance.

**Comment by waldekmastykarz** [comment]
What if we exposed some options, like failure rate globally in the proxy engine? We can already assume that there will be multiple types of plugins that might need to configure failure rate. What if we had a central option for it that they could all reuse? It doesn't solve the broader problem for a naming convention to avoid collisions but for the failure rate it would be a nice solutions that works across the board.

**Comment by garrytrinder** [comment]
I think this is a good compromise on the failure rate option.

**Comment by sebastienlevert** [comment]
Agree! Basically, we could simply offer a "options council" where we could offer to "promote" options to global scopes when we feel it could be beneficial.

**Comment by waldekmastykarz** [comment]
For now I'll create a separate option to expose `--failure-rate` globally, and we'll close this issue. Thanks for your input all.
