### ISSUE TITLE
Define aka.ms links for all URLs used in Developer Proxy

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#180]
For all URLs that we use in the Developer Proxy, let's use aka.ms links so that we can change them if necessary without breaking old versions of Proxy.

--- original

First thing that comes to mind... Should we have a series of aka.ms links that we control to be able to change location of guidance docs if they ever change without re-releasing a new version of the proxy? That should apply to all links we link to.

_Originally posted by @sebastienlevert in https://github.com/microsoftgraph/msgraph-developer-proxy/issues/174#issuecomment-1419354782_

**Comment by garrytrinder** [comment]
We have four places where we use URLs in the guidance warnings.

https://github.com/microsoftgraph/msgraph-developer-proxy/blob/78be427903c95a9addf7aa0034c04002eb5278ac/msgraph-developer-proxy-plugins/Guidance/GraphBetaSupportGuidancePlugin.cs#L31

https://github.com/microsoftgraph/msgraph-developer-proxy/blob/78be427903c95a9addf7aa0034c04002eb5278ac/msgraph-developer-proxy-plugins/Guidance/GraphSelectGuidancePlugin.cs#L35

https://github.com/microsoftgraph/msgraph-developer-proxy/blob/78be427903c95a9addf7aa0034c04002eb5278ac/msgraph-developer-proxy-plugins/Guidance/ODataPagingGuidancePlugin.cs#L136-L140

https://github.com/microsoftgraph/msgraph-developer-proxy/blob/78be427903c95a9addf7aa0034c04002eb5278ac/msgraph-developer-proxy-plugins/MessageUtils.cs#L11-L14

I propose we create short links for the following

- learn.microsoft.com/graph/versioning-and-support#beta-version -> aka.ms/graph/proxy/guidance/beta
- learn.microsoft.com/graph/query-parameters#select-parameter -> aka.ms/graph/proxy/guidance/select
- learn.microsoft.com/graph/paging -> aka.ms/graph/proxy/guidance/paging
- aka.ms/move-to-graph-js-sdk -> aka.ms/graph/proxy/guidance/js-sdk

This would them be consistent with our current short links.

- aka.ms/graph/proxy
- aka.ms/graph/proxy/download

As an aside, note that the JavaScript SDK guidance is in the `MessageUtils` class. Should we move the `GetMoveToSdkUrl` to the `GraphSdkGuidancePlugin` class to be consistent with the other plugins?

**Comment by sebastienlevert** [comment]
Absolutely agree on the proposal!

**Comment by waldekmastykarz** [comment]
Nice summary. I wonder if guidance/js-sdk isn't too generic. JS SDK has a few features so what's the guidance referring to? Since the guidance we point to is referring specifically to migration I suggest we include that word in the URL for clarity.

**Comment by garrytrinder** [comment]
Fair comment @waldekmastykarz lets stick with the existing short link name but appended to `/graph/proxy/guidance/` prefix.

I've created new short links and raised a PR to update them.
