### ISSUE TITLE
Increase the default fault rate to 90

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#188]
I suggest that we increase the default fault rate from 50 to 90. If we assume, that after installing a tool many users don't change the settings, it could take a while until your calls get intercepted by the proxy, which could give an impression that it's not working. By increasing the fault rate, we increase the change of intercepting and responding to the call.

Any thoughts @sebastienlevert, @gavinbarron, @garrytrinder?

**Comment by garrytrinder** [comment]
Good idea, I’m fine with this suggestion 👍

**Comment by sebastienlevert** [comment]
I learned that 50% is already a pretty good start... Every other call will fail, which is good, right? 90% basically means your app might never load...

**Comment by sebastienlevert** [comment]
I understand, but man the experience of an app leveraging the Proxy becomes quite messy on the first run... I get it though.

**Comment by waldekmastykarz** [comment]
Perhaps seeing the call intercepted is enough. Let's leave it be for now and keep an eye out on it how our customers perceive the first-run experience.
