### ISSUE TITLE
Update exe properties

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#197]
We should consider adding product name and product version to the exe properties.

![image](https://user-images.githubusercontent.com/11563347/221159807-353f0dbc-16fa-47a0-91d2-eca1043352c6.png)

**Comment by gavinbarron** [comment]
Those should be populated! I think this is related #198

**Comment by waldekmastykarz** [comment]
#199 is the related PR

**Comment by waldekmastykarz** [comment]
Fixed:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/11164679/221837670-a1bb50c2-c60b-4540-aa30-c352f4613950.png">
