### ISSUE TITLE
[Bug]: Incorrect version and new version message

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#198]
v0.5.0-beta.2
Windows 11
PowerShell 7.3.2

When running the latest beta I am warned that a new version is available, but shows me the version that I am currently on.

![image](https://user-images.githubusercontent.com/11563347/221163328-2021d672-080e-453c-8a40-a546aec5ee0f.png)

As an aside, we should also change the URL in the message to use the `https://aka.ms/graph/proxy/download` link.

**Comment by waldekmastykarz** [comment]
This should be fixed by #199. Let's confirm if that's indeed the case

**Comment by waldekmastykarz** [comment]
Seems to be working as expected in v0.5
