### ISSUE TITLE
Feature suggestion: Target only single app

### ISSUE THREAD

**Issue by Tanddant** [microsoftgraph/msgraph-developer-proxy#227]
Whenever I'm using the developer proxy soo many apps start to break, - for instance I my teams client sort of breaks and I don't always get messages, and while I don't mind, my boss does for some reason!

A way to attach the proxy to only a single service would be awesome!

**Comment by waldekmastykarz** [comment]
Would it be sufficient if we asked you to provide the PIDs (process IDs) of the apps for which you'd like to intercept requests or is that too inconvenient and you'd want to be able to use the display names instead (with the caveat that there might be multiple instances of the same process and you'd be capturing too much)?

**Comment by Tanddant** [comment]
![WhyNotBothTakeBothGIF](https://user-images.githubusercontent.com/6947024/224268803-cef9ee33-d29e-4ebe-bc1f-d833310c052a.gif)


I mean, it's a devtool - a PID would be fine, but also cause an overhead if I stop my debugger and start it again, so perhaps both would be the best approach, because there's also the scenario of debugging a teams app where I don't want to break teams, just my app

**Comment by waldekmastykarz** [comment]
Hey @Tanddant, just wanted to let you know that we've just shipped v0.6 of the proxy with support for capturing traffic from just the selected processes (either by PID or name). Looking forward to hearing how you like it!

**Comment by Tanddant** [comment]
Hey @waldekmastykarz - I saw, it's awesome 😎

I'll let you know when I have time to play with it, maybe sometime after Easter 👌

**Comment by waldekmastykarz** [comment]
Perfect! I appreciate your help, and please don't hesitate to reach out if you have any questions or feedback
