### ISSUE TITLE
Allow specifying config file name

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#228]
Right now we're using a config file with a fixed name: appsettings.json. As we're expanding proxy's features, it would be beneficial to allow defining presets for different APIs and scenarios, eg: testing Microsoft Graph random errors, testing contoso app scalability on M365, testing SPO, testing Open AI API, testing contoso API, etc. While you could create a separate file for each of these scenarios already now, in order to use them, you'd have to rename appsettings.json to something else, then rename the specific preset to appsettings.json. When you're done, you'd have to revert your changes and rename the files back. It would be much more convenient if you could start proxy with a specific config file, eg: `mgdp --config my-preset.json`, and use appsettings.json as the default settings when no config has been specified.

**Comment by waldekmastykarz** [comment]
What do you think @sebastienlevert @gavinbarron @garrytrinder?

**Comment by gavinbarron** [comment]
I like it!

**Comment by garrytrinder** [comment]
All good with me.

Great suggestion 👍🏻
