### ISSUE TITLE
Update proxy UI

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#235]
I had another look at our UI, and thought of a few ways how we could make it a bit easier on the eye and take less room in the terminal. Here are a few ideas.

This is how our UI looks like right now:

![Dev-Proxy-blog-image-1](https://user-images.githubusercontent.com/11164679/227901275-6f88140e-834a-4720-8221-d9c48b35ecd8.png)

Notice the bulky labels `[ REQUEST ]` and boxes with square corners that push the actual content to the right.

Here's some ideas for improving it.

1. What if used shorter and lowercase labels:

<img width="1162" alt="Screenshot 2023-03-25 at 20 35 50" src="https://user-images.githubusercontent.com/11164679/227901644-c632e5a8-c1cc-4e55-ac32-29d3fade485f.png">

We still get nice emphasis on the different types of messages that we log, but don't take too much screen estate from the actual log message.

2. To make the boxes a bit easier on the eyes, we could round their corners:

<img width="736" alt="Screenshot 2023-03-26 at 19 47 21" src="https://user-images.githubusercontent.com/11164679/227901825-7579c6f4-2c77-4a57-8474-22e1869556dc.png">

3. With labels indicating multi-line messages, what if we'd got rid of boxes altogether and use only indenting as a visual cue for which lines belong together. Then we could indicate the context URL with a special sign like

3a) braille dots

<img width="737" alt="Screenshot 2023-03-26 at 19 58 49" src="https://user-images.githubusercontent.com/11164679/227902149-aa9c1fa5-21a5-4b75-bfc4-65b6995ad225.png">

3b) or a chevron

<img width="731" alt="Screenshot 2023-03-26 at 19 56 19" src="https://user-images.githubusercontent.com/11164679/227902223-abb7135e-9866-4b04-9fa8-1c56e3d4043f.png">

I'd love to hear what you think @sebastienlevert @gavinbarron @garrytrinder

**Comment by gavinbarron** [comment]
I like the idea of removing the `[]` characters from the labels. 
As to the multi-line indicators, I like having the bracketing, the rounded ones do look a bit nicer though.

**Comment by waldekmastykarz** [comment]
Making the UI configurable at this stage would be quite challenging, because it would require us to properly expose string interpolating/templating, coloring, etc. I suggest we take this on for the future. For now, I like your proposal of using option no. 2 which is a minor change while a great improvement. I'll submit a PR with the necessary changes. Thanks!

**Comment by garrytrinder** [comment]
I think removing the brackets `[ ]` from the labels is a good suggestion. They feel redundant with the colour backgrounds in place.

The changes proposed to the text casing, text alignment and multi-line indicators however don't really make much difference to me. Those feel like user preference.
