### ISSUE TITLE
Re-using the Retry-After behavior across multiple plugins

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-developer-proxy#239]
We see multiple plugins doing the same (Rate Limiting, Chaos, etc.) with 429. We should have a better re-use of these capabilities.

**Comment by waldekmastykarz** [comment]
Specifically, it's about reusing the logic to forcefully fail requests that don't adhere to retry-after returned on 429 responses.

**Comment by waldekmastykarz** [comment]
Here, we also need to accommodate the difference in how each plugin might want to throttle: based on workload (Microsoft Graph), based on endpoint (monetized Teams APIs on Graph), host name (generic chaos).
