### ISSUE TITLE
[Feedback]: Mock responses with an adaptive card extension

### ISSUE THREAD

**Issue by a1mery** [microsoftgraph/msgraph-developer-proxy#258]
### Description

I've used the Microsoft Graph Developer proxy to mock responses for the graph API calls made in a adaptive card extension.
It was particularly useful to mock "likes" on SharePoint pages, instead of logging in as different users to do so.

Really nice that you can edit the `responses.json` file without restarting the proxy !

### Expected behaviour

Not applicable

### Actual behaviour

Not applicable

### Steps to reproduce

Not applicable

### Microsoft Graph Developer Proxy Version

0.7.0

### Operating system (environment)

Windows

### Shell

PowerShell

**Comment by waldekmastykarz** [comment]
Thank you for the kind words, @a1mery, and awesome to hear that you find the proxy so helpful! Thank you for sharing the scenarios where you're using the proxy. Is there anything else that we could improve for you?

**Comment by a1mery** [comment]
Well, maybe it would be good to set the default value for the `failureRate` setting as `0` or display the value in the terminal output.
In my scenario, I only wanted to mock responses so I started the proxy using: `mgdp --mocks-file 'path of the responses file'`.
And while I was testing my app, I was also doing some actions on the SharePoint admin portal. I didn't understand why some screens wouldn't load ("Acvite sites" for instance). It took me a few minutes to understand that it was related to the proxy :) So I restarted the proxy using: `mgdp --mocks-file 'path of the responses file' --failure-rate 0` instead and it worked !
I went back to the tutorial and realized it was clearly stated that the default value was `50` but in my opinion it could be better to change the default value.

Just a minor suggestion for a tool that is making my developer life much easier !

**Comment by waldekmastykarz** [comment]
Thank you! This is a great suggestion! An alternative that works already now is to disable the random error plugin, by setting its `enabled` value to `false`. That way, you can keep all the configuration in place, but have the plugin disabled and not affecting your requests.
