### ISSUE TITLE
🙏 Change keyboard shortcut to stop proxy to CTRL+C from ENTER

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/msgraph-developer-proxy#47]
The general practice to terminate any console process is to use <kbd>Ctrl</kbd>+<kbd>c</kbd> one more multiple times. Even in the SharePoint world, see SPFx's **gulp serve**, yo teams **gulp serve** & **gulp ngrok-serve**, etc.

Please be consistent... currently the instructions say to press <kbd>ENTER</kbd>... please change to follow established conventions for console apps: <kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by gavinbarron** [comment]
Thanks for the feedback @andrewconnell that is a great suggestion.
