### ISSUE TITLE
[How-to guide]: Update my application code to use Microsoft Graph JavaScript SDK

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#59]
We should move the [Move to the Graph JS SDK](https://github.com/microsoftgraph/msgraph-developer-proxy/blob/main/msgraph-developer-proxy/Move-to-JS-SDK.md) guidance to our wiki so that it's in the same place as the rest of our docs and we can update it more easily.

**Comment by garrytrinder** [comment]
I agree, the question is where does it go in the Wiki. Is this a `Tutorial` aimed at a beginner, or a `How-to guide` where there is some assumed knowledge in place?

**Comment by waldekmastykarz** [comment]
I'd say it's a how-to guide

**Comment by garrytrinder** [comment]
In that case, I've changed the title to be more scenario/task based.

I wonder if we should also have a page in the Background information section that explains why we suggest using the SDK in the tool. This could be a one pager which explains the benefits/advantages and refers to the How to guide as a CTA.

**Comment by waldekmastykarz** [comment]
> I wonder if we should also have a page in the Background information section that explains why we suggest using the SDK in the tool. This could be a one pager which explains the benefits/advantages and refers to the How to guide as a CTA.

Definitely! That's pillar content that we need to have for other initiatives as well, not just for the proxy.

**Comment by garrytrinder** [comment]
Page added to wiki.

https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Update-my-application-code-to-use-Microsoft-Graph-JavaScript-SDK

**Comment by garrytrinder** [comment]
Target has been updated on aka.ms/move-to-graph-js-sdk short link to new location in wiki.
