### ISSUE TITLE
[How-to Guide]: Use the Microsoft Graph Developer Proxy with national cloud deployments

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#60]
Microsoft Graph Developer Proxy supports the use of [national cloud deployments](https://learn.microsoft.com/en-us/graph/deployments), however we don't call out what steps developers need to take to take advantage of this in our guides, we should add a How-to guide to cover this.

**Comment by waldekmastykarz** [comment]
Good catch! Seems like we totally missed that 😊

**Comment by waldekmastykarz** [comment]
Following this spec: https://github.com/microsoftgraph/msgraph-developer-proxy/pull/70 we'll be removing this functionality in favor of URLs that are controlled by users. Because of this, we no longer need this documentation.
