### ISSUE TITLE
Project-specific config

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#62]
Currently, developers can save proxy configuration centrally by updating the `appSettings.json` file, which apply these settings globally. However, there may be occasions where developers want to save different configurations for specific projects, which we currently don't support.

We should consider, in the same way which we do for `responses.json`, providing a project specific way of configuring the proxy.

**Comment by waldekmastykarz** [comment]
Do you see this being a hierarchy of configs, eg. app settings in app folder < app settings in working folder < command line args, or rather project-specific config cancelling global config?

**Comment by waldekmastykarz** [comment]
Given the implementation of #228 where we can specify config file path, do we still need this feature or is the functionality already covered by #228?

**Comment by garrytrinder** [comment]
It's covered by #228, closing.
