### ISSUE TITLE
Improve readability of console output

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-developer-proxy#68]
Right now, it's hard to discern the different types of messages in the proxy. What's more, indenting messages makes them even harder to read. We should consider color-coding different types of messages.

Here's our output at the moment:

<img width="975" alt="image" src="https://user-images.githubusercontent.com/11164679/206721857-75055770-b41e-4fd6-b1a9-df3777c9f413.png">

In comparison, here's an example from the [Node proxy](https://github.com/TooTallNate/proxy):

<img width="742" alt="image" src="https://user-images.githubusercontent.com/11164679/206721366-5647e8f7-ef5b-42e4-904f-12fb307885b4.png">

This is debug output where arrows describe different types of messages (proxy response →/request ←, pass-thru response/request ↑).

Let's look at the different types of messages we log and how we could code them to make them easier to follow.

**Comment by gavinbarron** [comment]
I like it! 
We do need to ensure that we use some iconography as well as color for the different types of messages we're outputting for accessibility reasons.
Open question for this, can we find enough text icons in the default character sets across Windows/Linux/Mac or do we need to have the users install a nerdfont?

**Comment by garrytrinder** [comment]
Great suggestion @waldekmastykarz a clearer output will really help.

> can we find enough text icons in the default character sets across Windows/Linux/Mac or do we need to have the users install a nerdfont?

I think we should stick to using text icons and colour coding, but we could also check to see what the emoji support is across the three OS as an alternative to text icons.

**Comment by waldekmastykarz** [comment]
I suspect the lowest common denominator will be cmd on Windows or remote sessions when using the proxy in a container. Let's propose a few designs through a simple console app that we could run across the different terminals to verify it's working as intended. If we choose to use something based on an optional dependency like nerdfont then we should give folks an option to have a readable output without it.

**Comment by waldekmastykarz** [comment]
In the following comments I'll add screenshots of some ideas so far. Use 👍 to vote on your preferred UI

**Comment by waldekmastykarz** [comment]
Option 1

Warp:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/11164679/208642997-292a033a-283d-4385-bacc-29ea98e348d8.png">

Built-in VSCode terminal:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/11164679/208643248-a53d2d85-3279-47ce-ac88-63413fbf67fa.png">

**Comment by waldekmastykarz** [comment]
### Option 2
Colored ASCII icons

Warp:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/11164679/208643338-2da45394-533c-4a1b-8bf7-53a3495b48cb.png">

Built-in VSCode terminal:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/11164679/208643445-cfc38f53-1c82-4fb4-ab44-3c77754a0439.png">

**Comment by waldekmastykarz** [comment]
### Option 3
Inverted ASCII icons

Warp:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/11164679/208643677-e659d9a2-dc3a-4b09-a7bc-cc3ad0336506.png">

Built-in VSCode terminal:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/11164679/208643739-4f3c9e8e-7699-4f6c-8299-cb0e68d75acd.png">

**Comment by waldekmastykarz** [comment]
### Option 4
Emoji icons with colored text

Warp:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/11164679/208643911-c5a69e01-7281-4d85-b866-82e02d8c3adc.png">

Built-in VSCode terminal:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/11164679/208644000-ee124131-bc9b-48dd-a6dc-199e9f218cd6.png">

**Comment by waldekmastykarz** [comment]
### Option 5

Indented

Warp:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/11164679/208644097-c661b8ed-b49a-4f2b-831f-491e1920eefb.png">

Built-in VSCode terminal:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/11164679/208644148-f485efc1-63f5-49c0-843c-ee993282848d.png">

**Comment by waldekmastykarz** [comment]
### Option 6

Colored labels and text

Warp:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/11164679/208644274-48a5fcb6-6a39-4bbd-9c40-9c543cb166f1.png">

Built-in VSCode terminal:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/11164679/208644337-f780b776-fad4-4076-8ced-da7db55db3a8.png">

**Comment by waldekmastykarz** [comment]
### Option 7

Colored labels

Warp:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/11164679/208644455-a321acb4-f4e7-49ea-95fb-9069a8bc11ec.png">

Built-in VSCode terminal:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/11164679/208644532-45fae2b2-2897-44a9-9fe6-a9a74793feab.png">

**Comment by waldekmastykarz** [comment]
### Option 8

Inverted labels

Warp:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/11164679/208644652-8d2460ad-df07-48f7-bccd-a49b900b6fad.png">

Built-in VSCode terminal:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/11164679/208644719-44643495-d305-4d5e-a8b8-7ae651584734.png">

**Comment by waldekmastykarz** [comment]
### Option 9

Short color labels

Warp:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/11164679/208644835-0b15a666-3305-4962-aebc-1b0890b2b666.png">

Built-in VSCode terminal:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/11164679/208644882-30769d0e-d28d-44af-9752-962955a76209.png">

**Comment by gavinbarron** [comment]
Great work on producing these options! 
I really like 1 & 8.

**Comment by tmeckel** [comment]
Definitely Option 8 because it's the most explicit and easy to follow with the eyes

**Comment by waldekmastykarz** [comment]
Thank you for your opinion and the reasoning @tmeckel 😊

**Comment by MrDrSushi** [comment]
Hey @waldekmastykarz  your ideas are great, I don't know if I can improve them, if I may add, I would suggest using the Nerd Font for the icons, we would gain more "real state" in the output and I guess, a better visual representation, I've been using Oh-My-Posh for quite some time now and it was the first thing that came to my mind when I was reading your suggestions.

**Comment by waldekmastykarz** [comment]
Thanks for chiming in @MrDrSushi. That's a great idea, like you mentioned, to get some more screen estate back. The only limitation I see is that not everyone might have the font installed, so we'd have to build it as a +1, where we have a baseline symbols that work for everyone. That said, do you have suggestions for icons to use for the different types of messages?

**Comment by MrDrSushi** [comment]
To be honest, the same thought crossed my mind, and for that reason I think the NerdFont should be an optional thing since it is  a +1 (I can't agree more with you) - not everybody will want to go this route if NerdFont is a requirment, I think for devs like myself that live on Terminal screens + Visual Studio Code plugins, having a tool that embraces the current Windows Terminal is an big advantage.

if we could have an option for "settings" we could define our own "icons", then the output would be rendered according to what we are using (NerdFont or not), under whatever I'm using classic MS-DOS Prompt, Linux Terminal, or Windows Terminal + NerdFont + Oh-My-Posh as example.

**Comment by waldekmastykarz** [comment]
> if we could have an option for "settings" we could define our own "icons", then the output would be rendered according to what we are using (NerdFont or not), under whatever I'm using classic MS-DOS Prompt, Linux Terminal, or Windows Terminal + NerdFont + Oh-My-Posh as example.

A good way about it would be for us to offer a binary switch for NerdFont on|off. If it's disabled, you get whatever works fine in the lowest common denominator. When it's on, you get default icons from us. On top, we'd offer the ability to customize with your own icons. How does that sound?

**Comment by waldekmastykarz** [comment]
I took a look at NerdFont and how it could fit our output styling. The biggest issue is readability which seem to differ per font. Here are some examples:

Cascadia Cove 13pt in Warp on macOS:
<img width="701" alt="image" src="https://user-images.githubusercontent.com/11164679/209340263-db61ee9d-b9b4-412b-941c-5a2f07c9f756.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/11164679/209340324-97c67eba-78df-4178-b32f-da40627e01f3.png">

Hack 13pt in Warp on macOS:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/11164679/209340407-f62da87e-e1d1-4dc6-896a-3e04a9a02933.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/11164679/209340437-b883f1f9-d7f1-4773-8fb5-dafb0b190f9a.png">

Cascadia Code 12px in VSCode Terminal on macOS:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/11164679/209340609-3a7b4aaf-77dc-4c5c-8999-bb3470e917b9.png">

Here's an example of some icons in our output:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/11164679/209340774-a7b35267-1b9f-42b6-a9bc-f1933f503a2e.png">

You can barely see them and I wonder if it makes sense to investigate them further.

**Comment by waldekmastykarz** [comment]
Here's how the output could look like with Nerd Fonts:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/11164679/209345499-bfbf2427-9f47-4927-ad26-385ca67ebe5c.png">

The key part is that user must be using a non-Mono Nerd Font, because for Mono fonts icons are [illegible](https://github.com/Powerlevel9k/powerlevel9k/issues/430).

Here are some alternative icons that we could consider:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/11164679/209345665-1297c3a1-891d-4e4e-9eef-06aa18d141aa.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/11164679/209345715-73605bb9-5bbc-4959-9377-35782c804ec2.png">

**Comment by waldekmastykarz** [comment]
We're refactoring the proxy to separate its core/runtime from the different features. This will allow us to organize the code better and allow others to add custom functionality #58.

We noticed, that this causes the different messages to run out of band:

![image (3)](https://user-images.githubusercontent.com/11164679/209346062-91c5492e-ba21-4e62-a12c-83115354cede.png)

To address this, we're thinking about two approaches:

1. To every captured request, assign an ID and prepend it to each message we log. This would look a bit like this:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/11164679/209346211-072fa8ed-59fd-4e54-9f4e-a21da30c2818.png">

While the output is condensed, it requires you to look up the URL for each ID which could be cumbersome if you have an app that issues many requests.

2. To every message append the context URL:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/11164679/209346412-1f7a3310-90e6-4f00-89e6-2d8b3b15c424.png">

We use bands to group the related lines together and for each message you can quickly see to which request it applies. The downside is that it expands the log with the request method and URL for each message we log.

It would be great to hear your thoughts

**Comment by waldekmastykarz** [comment]
Right now, my thinking goes towards:

- banded output (rather than assigning an ID for each request)
- icon mode with icons Nerd Font or ascii icons with whole lines colored ([option 1](https://github.com/microsoftgraph/msgraph-developer-proxy/issues/68#issuecomment-1359131547))
- text mode following [option 8](https://github.com/microsoftgraph/msgraph-developer-proxy/issues/68#issuecomment-1359139733)

### Rationale:

- banded output allows you to directly see to which request each message relates, without having to scroll back and match the ID to a URL
- when you start using the Proxy or you don't use it that often, the different icons could be cryptic, so text mode is self-explanatory
- after you've used the Proxy for a while, you might want to condense the output and use icons instead of text labels
- if you care about your terminal experience, you likely have a Nerd Font installed and we should use it when possible to give you a great experience
- if you don't have Nerd Font, ascii icons are the next best thing

🙋‍♂️ Thinking of it, should we combine option 8 (text labels) with option 1 (icons) so that you can start getting used to icons and at some point remove the text label?

**Comment by MrDrSushi** [comment]
> We're refactoring the proxy to separate its core/runtime from the different features. This will allow us to organize the code better and allow others to add custom functionality #58.
> 
> We noticed, that this causes the different messages to run out of band:
> 
> ![image (3)](https://user-images.githubusercontent.com/11164679/209346062-91c5492e-ba21-4e62-a12c-83115354cede.png)
> 
> To address this, we're thinking about two approaches:
> 
> 1. To every captured request, assign an ID and prepend it to each message we log. This would look a bit like this:
> 
> <img alt="image" width="995" src="https://user-images.githubusercontent.com/11164679/209346211-072fa8ed-59fd-4e54-9f4e-a21da30c2818.png">
> 
> While the output is condensed, it requires you to look up the URL for each ID which could be cumbersome if you have an app that issues many requests.
> 
> 2. To every message append the context URL:
> 
> <img alt="image" width="760" src="https://user-images.githubusercontent.com/11164679/209350972-617ea9ee-3e26-405d-af59-415287d876f4.png">
> 
> We use bands to group the related lines together and for each message you can quickly see to which request it applies. The downside is that it expands the log with the request method and URL for each message we log.
> 
> **It would be great to hear your thoughts**

I'm intrigued, both options are really good, I guess testing will determine which one is the best when troubleshooting things in a dev/production environment

**Comment by ValerasNarbutas** [comment]
> Right now, my thinking goes towards:
> 
> * banded output (rather than assigning an ID for each request)
> * icon mode with icons Nerd Font or ascii icons with whole lines colored ([option 1](https://github.com/microsoftgraph/msgraph-developer-proxy/issues/68#issuecomment-1359131547))
> * text mode following [option 8](https://github.com/microsoftgraph/msgraph-developer-proxy/issues/68#issuecomment-1359139733)
> 
> ### Rationale:
> * banded output allows you to directly see to which request each message relates, without having to scroll back and match the ID to a URL
> * when you start using the Proxy or you don't use it that often, the different icons could be cryptic, so text mode is self-explanatory
> * after you've used the Proxy for a while, you might want to condense the output and use icons instead of text labels
> * if you care about your terminal experience, you likely have a Nerd Font installed and we should use it when possible to give you a great experience
> * if you don't have Nerd Font, ascii icons are the next best thing
> 
> 🙋‍♂️ Thinking of it, should we combine option 8 (text labels) with option 1 (icons) so that you can start getting used to icons and at some point remove the text label?

I really like option 1, 7 and 8 are equally good also

**Comment by garrytrinder** [comment]
> 🙋‍♂️ Thinking of it, should we combine option 8 (text labels) with option 1 (icons) so that you can start getting used to icons and at some point remove the text label?

I love this approach, 💯 in agreement with you.

**Comment by rabwill** [comment]
Loved option 7 & 9. Great thread everyone. I came to the repos to suggest readability. So glad to see the maintainers are already thinking about.

**Comment by martinlingstuyl** [comment]
Looks awesome guys, I like nerd fonts, but it does not make it clearer perse. I'd say: just text labels (8) by default, and allow a configuration option to change to icon mode. 

Fully in favor of the banded idea as well. 🤙
