### ISSUE TITLE
[Get started]: Update step to safety shut down the proxy

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#78]
Following the closure of #47 we changed the way developers should safely close down the proxy to using Ctrl + C.

We should update the section in the tutorial to reflect this change.

https://github.com/microsoftgraph/msgraph-developer-proxy/wiki/Using-the-Microsoft-Graph-Developer-Proxy-for-the-first-time#-stop-the-proxy-process-safely

**Comment by waldekmastykarz** [comment]
Let's update the guidance after we released v0.3.0. For the current release, the guidance is correct.

**Comment by garrytrinder** [comment]
Ah yes, good call @waldekmastykarz 😊

**Comment by garrytrinder** [comment]
All references in docs updated to reflect the new way to close the proxy safely.
