### ISSUE TITLE
New version message

### ISSUE THREAD

**Issue by garrytrinder** [microsoftgraph/msgraph-developer-proxy#79]
When developers are using an old version of the proxy, we should consider providing a message to tell them that and that they should update to the latest version, providing a link to the latest release.

**Comment by waldekmastykarz** [comment]
We have this implemented already here: https://github.com/microsoftgraph/msgraph-developer-proxy/blob/c35de02cfdc3f3e78afd4a569f01ab9b671a6318/msgraph-developer-proxy/ProxyCommandHandler.cs#L44-L52
