### ISSUE TITLE
Clarification on manual app registration in sample readme

### ISSUE THREAD

**Issue by leeford** [microsoftgraph/msgraph-developer-proxy#90]
If you choose to create the app registration manually by following the [readme](https://github.com/microsoftgraph/msgraph-developer-proxy/blob/main/samples/readme.md) under `samples`, it fails. 

It states that the display name **Microsoft Graph Developer Proxy Samples** is invalid.

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/472320/208527307-dd816750-7374-4784-bce9-7c965cb488f6.png">

This only applies when you set the app registration to multi-tenant (single-tenant allows the name), but the sample uses the `/common/` endpoint, which I guess is why you don't need to specify the tenant ID along with the client ID in the `env.js` file. But, I cannot find mention of it being a multi-tenant app registration in the manual steps of the readme.

It should be noted if I use the display name `graph-developer-proxy-samples`, which is what the automated script uses, it works!

More than happy to issue a PR for this (if required), or if you would rather take a look yourselves.

**Comment by waldekmastykarz** [comment]
Thanks for pointing it out! If I'm not mistaken, it's because you're not allowed to use `Microsoft` in the name of an AAD app, which is why setting the name's failing. We'll review and fix the guidance. Thanks again for reporting this.

**Comment by garrytrinder** [comment]
Good catch @leeford thanks for reporting 👍🏻
